# general settings
name: StereoWaterdrop_NAFNet_Freq_LFE×1_SCAM_deform_param_L1SSIMLoss_128_midchan=32_100000_LOW
model_type: StereoImageCleanModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedStereoImage
    dataroot_gt: data/Middlebury/train/gt/left
    dataroot_lq: data/Middlebury/train/input/left
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [8]
    iters: [100000]
    gt_size: 128
    gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedStereoImage
    dataroot_gt: data/Middlebury/val/gt/left
    dataroot_lq: data/Middlebury/val/input/left
    io_backend:
      type: disk

    gt_size: 128
    gt_sizes: [128]

# network structures
network_g:
  type: StereoNAFNetFreqDEBlockSCAM
  img_channels: 3
  mid_channels: 32
  enc_blk_nums: [2, 2, 2, 2]
  middle_blk_num: 2
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 100000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [30000, 70000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
#  pixel_opt:
#    type: L1Loss
#    loss_weight: 1
#    reduction: mean
  pixel_opt:
    type: L1SSIMLoss
    loss_weight: 1
    l1_weight: 0.5       # L1损失的权重
    ssim_weight: 0.5     # SSIM损失的权重
    reduction: mean
    window_size: 11      # SSIM的窗口大小，可根据需要调整
    channel: 3           # 图像的通道数，彩色图像为3，灰度图像为1

# validation settings
val:
  window_size: 8
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
